# Pipeline's webservice host
host: http://localhost
# Pipeline's webservice port
port: 8181
# Pipeline's webservice path, as in HOST:PORT/PATH (e.g. http://localhost:8181/ws)
path: ws
# Timeout for requests to the webservice in seconds
timeout: 10
# Path of the DAISY Pipeline app or the pipeline launch script to use the webservice.
# If empty or only containing 'DAISY Pipeline', the app is searched in the PATH
#app_path:
# Client key for authenticated requests
#client_key:
# Client secrect for authenticated requests
#client_secret:

# Print debug messages
debug: false
# Start the webservice or the DAISY Pipeline app in the local computer if it is not running
starting: false